name: Static Analysis

on: ['push', 'pull_request']

jobs:
  static:
    name: Static Tests

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency-version: [prefer-lowest, prefer-stable]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install Dependencies
      run: composer update --prefer-stable --no-interaction --no-progress --ansi

    - name: Types
      run: composer test:types

    - name: Style
      run: composer test:lint
